defaultSemverRangePrefix: ''

nodeLinker: node-modules

packageExtensions:
  react-cosmos-plugin@*:
    dependencies:
      glob: '*'
      path: '*'
      resolve-from: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-sources.cjs
