defaultSemverRangePrefix: ''

logFilters:
  # Make Yarn fail the install if there are any missing peerDeps
  # https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
  - code: 'YN0002'
    level: error

nodeLinker: node-modules

packageExtensions:
  '@nivo/annotations@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/axes@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/bar@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/bump@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/circle-packing@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/core@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/geo@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/heatmap@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/line@*':
    peerDependencies:
      react-dom: '*'
  '@nivo/pie@*':
    peerDependencies:
      react-dom: '*'
      prop-types: '*'
  '@nivo/tooltip@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@nivo/treemap@*':
    peerDependencies:
      react-dom: '*'

  # Possible PR should be made to plugins compat database or to this plugin
  '@octokit/rest@*':
    dependencies:
      '@octokit/core': '*'

  # Possible PR should be made to plugins compat database or to react-cosmos for these Cosmos items
  react-cosmos@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
      webpack: '*'
    peerDependenciesMeta:
      '@types/express':
        optional: true
  react-cosmos-shared2@*:
    peerDependencies:
      react: '*'
      react-dom: '*'

  # Possible PR should be made to plugins compat database or to reakit for these Reakit items
  reakit-warning@*:
    peerDependencies:
      react-dom: '*'

  # Possible PR should be made to plugins compat database or these fela plugins
  fela-plugin-placeholder-prefixer@*:
    peerDependencies:
      fela: '*'
  react-fela@*:
    peerDependencies:
      fela: '*'

  # Check back to see if this is still needed after the react-scripts v5 update
  react-dev-utils@*:
    peerDependencies:
      webpack: '*'
    peerDependenciesMeta:
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
