# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

  # Default build command.
  command = "yarn cascara build && yarn docs build"
  functions = "out_functions"
  publish   = "out_publish"

  # Directory with the serverless Lambda functions to deploy to AWS.
  # functions = "functions/"

  # We can define other environment variables here as well... do not include secret tokens!
  environment = { NODE_VERSION = "14.5.0" }
