[[plugins]]
package = "netlify-plugin-cache-nextjs"

    [plugins.inputs]
        # The path to the build directory
        build_dir_path = "docs"

[build]

  # Default build command.
  command = "yarn cascara build && yarn docs build"

  # Directory for build output
  publish = "docs/build/"

  # Directory with the serverless Lambda functions to deploy to AWS.
  # functions = "functions/"

  # We can define other environment variables here as well... do not include secret tokens!
  environment = { NODE_VERSION = "14.5.0" }
