version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
  mem: circleci/rememborb@0.0.2

parameters:
  installed-key:
    type: string
    default: cascara-MONOREPO_INSTALLED-{{ .Revision }}

aliases:
  - &is_main
    equal: [main, << pipeline.git.branch >>]
  - &is_develop
    equal: [develop, << pipeline.git.branch >>]

commands:
  deploy-vercel:
    description: Deploys our docs to Vercel
    parameters:
      vercel-deploy-hook:
        type: string
        default: $VERCEL_DEPLOY_DEVELOP
    steps:
      - run:
          name: Deploy Vercel
          command: curl -X POST << parameters.vercel-deploy-hook >>

job_executor: &job_executor
  executor:
    name: node/default
    tag: '12.13.0'

post_steps: &post_steps
  post-steps:
    - slack/notify:
        event: fail
        template: basic_fail_1

jobs:
  install:
    <<: *job_executor
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn install --immutable
          pkg-manager: yarn
      - run: |
          yarn changeset status --output=./versions.json
          printf "$(node tooling/getNextVersions.js)"
      - mem/remember:
          env_var: SLACK_MESSAGE
          value: $(printf "$(node tooling/getNextVersions.js)")
      - run: echo "${SLACK_MESSAGE}"
      - run:
          name: Prepare Packages
          command: yarn workspaces foreach run prepare
      - store_artifacts:
          path: ./node_modules/@espressive/cascara # check to see why we do not have @espressive/cascara
      - save_cache:
          key: << pipeline.parameters.installed-key >>
          paths:
            - ~/

  lint:
    <<: *job_executor
    steps:
      - restore_cache:
          key: << pipeline.parameters.installed-key >>
      - run:
          name: Run Eslint
          command: yarn lint --format junit --output-file ./coverage/eslint.xml
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  test:
    <<: *job_executor
    steps:
      - restore_cache:
          key: << pipeline.parameters.installed-key >>
      - run:
          name: Run Unit Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage

  build-cascara:
    <<: *job_executor
    steps:
      - restore_cache:
          key: << pipeline.parameters.installed-key >>
      - run:
          name: Build Cascara Runtimes
          command: yarn cascara build

  build-cosmos:
    <<: *job_executor
    steps:
      - restore_cache:
          key: << pipeline.parameters.installed-key >>
      - run:
          name: Build Cosmos
          command: yarn cosmos:build
      - store_artifacts:
          path: ./build/cosmos
          destination: cosmos

  publish:
    <<: *job_executor
    steps:
      - restore_cache:
          key: << pipeline.parameters.installed-key >>
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_PACKAGE_DEPLOY_FINGERPRINT
      - run:
          name: Set Up Git config
          command: |
            git config --global -l
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
      - run:
          name: Get Changeset Status
          command: yarn changeset status --output=./versions.json
      # - mem/remember:
      #     env_var: SLACK_MESSAGE
      #     value: $(echo node ./tooling/getNextVersions.js)
      - when:
          condition: *is_develop
          steps:
            - run:
                name: Publish Next Snapshot
                command: | # DO NOT COMMIT CHANGES FOR SNAPSHOT RELEASES!!!
                  yarn changeset version --snapshot next
                  yarn changeset publish --tag next
            - slack/notify:
                event: pass
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": $(echo node ./tooling/getNextVersions.js)
                      }
                    ]
                  }
      - when:
          condition: *is_main
          steps:
            - run:
                name: Publish Full Release
                command: |
                  yarn changeset version
                  git add .
                  git commit -m "Publish Full Release"
                  yarn changeset publish
                  git push --follow-tags
            - slack/notify:
                event: pass
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": $(echo node ./tooling/getFullVersions.js)
                      }
                    ]
                  }

install_pre_steps: &install_pre_steps
  pre-steps:
    - run: echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" >> ~/.npmrc
    - run: echo "@espressive:registry=https://npm.pkg.github.com" >> ~/.npmrc

requires_install: &requires_install
  requires:
    - install

requires_tests: &requires_tests
  requires:
    - lint
    - test

filter_main_and_dev: &filter_main_and_dev
  filters:
    branches:
      only:
        - main
        - develop

filter_tags: &filter_tags
  filters:
    # Ignore all branch commits
    branches:
      ignore: /.*/
    tags:
      only: /^@espressive.*/

workflows:
  build-and-test:
    jobs:
      - install:
          <<: *install_pre_steps
          <<: *post_steps
      - lint:
          <<: *post_steps
          <<: *requires_install
      - test:
          <<: *post_steps
          <<: *requires_install
      - build-cascara:
          <<: *post_steps
          <<: *requires_tests
      - build-cosmos:
          <<: *post_steps
          <<: *requires_tests
      - publish:
          <<: *filter_main_and_dev
          <<: *post_steps
          requires:
            - build-cascara
            - build-cosmos
# publish-tagged-packages:
#   jobs:
#     - install:
#         <<: *filter_tags
#         <<: *install_pre_steps
#         <<: *post_steps
#     - publish-packages:
#         <<: *filter_tags
#         <<: *post_steps
#         <<: *requires_install
