version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                  - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                  - ~/.cache/yarn
            - persist_to_workspace:
                root: ~/
                paths:
                  - '*'
            - slack/status:
                fail_only: true
                failure_message: ':alert: A $CIRCLE_JOB job has failed!'
                mentions: 'bje'
  test:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/
            - run:
                name: Unit Tests
                command: yarn test
            - slack/status:
                fail_only: true
                failure_message: ':alert: A $CIRCLE_JOB job has failed!'
                mentions: 'bje'
  build:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/
            - run:
                name: Build
                command: yarn test
            - slack/status:
                fail_only: true
                failure_message: ':alert: A $CIRCLE_JOB job has failed!'
                mentions: 'bje'
  deploy-docs:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/
            - run:
                name: Build
                command: yarn test
            - slack/status:
                fail_only: true
                failure_message: ':alert: A $CIRCLE_JOB job has failed!'
                mentions: 'bje'
workflows:
  build-and-test:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy-docs:
          requires:
            - install
          filters:
            branches:
              only: main
