version: 2.1

orbs:
  node: circleci/node@3.0.1
  slack: circleci/slack@3.4.2

jobs:
  install:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - save_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/node_modules
            # - /home/circleci/project/packages/*/node_modules
            - /home/circleci/project/packages/cascara/node_modules
            - /home/circleci/project/packages/framer/node_modules
            - /home/circleci/project/packages/tokens/node_modules
            # - /home/circleci/project/utils/*/node_modules
            - /home/circleci/project/utils/babel-preset-espressive/node_modules
            - /home/circleci/project/utils/eslint-config-espressive/node_modules
            - /home/circleci/project/utils/legacy-css/node_modules
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  lint:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Run Eslint
          command: yarn lint --format junit --output-file ./coverage/eslint.xml
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  test:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Run Unit Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-cascara:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Build Cascara Runtimes
          command: make
      - save_cache:
          key: cascara-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/dist
      - store_artifacts:
          path: /home/circleci/project/packages/cascara/dist
          destination: dist
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-cosmos:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          name: Build Cosmos
          command: yarn cosmos:build
      - store_artifacts:
          path: ./build
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-docs:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - restore_cache:
          key: node_modules-CASCARA-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - restore_cache:
          key: cascara-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/dist
      - run:
          name: Build Docs
          command: yarn docs build
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

workflows:
  build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-cascara:
          requires:
            - install
      - build-cosmos:
          requires:
            - lint
            - test
      - build-docs:
          requires:
            - build-cascara
            - lint
            - test
