version: 2.1

orbs:
  node: circleci/node@4.0.1
  slack: circleci/slack@3.4.2

jobs:
  install:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
          paths:
            - ~/
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'here'

  lint:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Run Eslint
          command: yarn lint --format junit --output-file ./coverage/eslint.xml
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'here'

  test:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Run Unit Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'here'

  build-cascara:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Build Cascara Runtimes
          command: make
      - save_cache:
          key: cascara-CASCARA_RUNTIMES-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/dist
      - store_artifacts:
          path: ./packages/cascara/dist
          destination: dist
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'here'

  build-cosmos:
    executor:
      name: node/default
      tag: '12.0.0'
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Build Cosmos
          command: yarn cosmos:build
      - store_artifacts:
          path: ./build/cosmos
          destination: cosmos
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'here'

  # build-docs:
  #   executor:
  #     name: node/default
  #     tag: '12.0.0'
  #   steps:
  #     - restore_cache:
  #         key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
  #     - restore_cache:
  #         key: cascara-CASCARA_RUNTIMES-{{ .Revision }}-{{ checksum "yarn.lock" }}
  #     - run:
  #         name: Build Docs
  #         command: yarn cascara build && yarn docs build
  #     - slack/status:
  #         fail_only: true
  #         include_project_field: false
  #         mentions: 'here'

workflows:
  build-and-test:
    jobs:
      - install:
          pre-steps:
            - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_INSTALL_AUTH_TOKEN}" >> ~/.npmrc
            - run: echo "@espressive:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-cascara:
          requires:
            - install
      - build-cosmos:
          requires:
            - lint
            - test
      # - build-docs:
      #     requires:
      #       - build-cascara
      #       - lint
      #       - test
