version: 2.1

orbs:
  node: circleci/node@4.0.1
  slack: circleci/slack@4.2.1

job_executor: &job_executor
  executor:
    name: node/default
    tag: '12.13.0'

post_steps: &post_steps
  post-steps:
    - slack/notify:
        custom: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "[JOB FAILED] ${CIRCLE_BRANCH}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Job*:\n${CIRCLE_JOB}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author*:\n${CIRCLE_USERNAME}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${CIRCLE_BUILD_URL}"
                  }
                ]
              }
            ]
          }
        event: fail

jobs:
  install:
    <<: *job_executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Prepare Packages
          command: yarn workspaces run prepare
      - store_artifacts:
          path: ./node_modules/@espressive/cascara # check to see why we do not have @espressive/cascara
      - save_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
          paths:
            - ~/

  lint:
    <<: *job_executor
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Run Eslint
          command: yarn lint --format junit --output-file ./coverage/eslint.xml
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  test:
    <<: *job_executor
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Run Unit Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage

  build-cascara:
    <<: *job_executor
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Build Cascara Runtimes
          command: yarn cascara build
      - save_cache:
          key: cascara-CASCARA_RUNTIMES-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/dist
      - store_artifacts:
          path: ./packages/cascara/dist
          destination: dist

  build-cosmos:
    <<: *job_executor
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Build Cosmos
          command: yarn cosmos:build
      - store_artifacts:
          path: ./build/cosmos
          destination: cosmos

  release:
    <<: *job_executor
    steps:
      - restore_cache:
          key: cascara-MONOREPO_INSTALLED-{{ .Revision }}
      - run:
          name: Publish Cascara
          command: yarn lerna version --no-private --conventional-commits --create-release github --yes

workflows:
  build-and-test:
    jobs:
      - install:
          pre-steps:
            - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_INSTALL_AUTH_TOKEN}" >> ~/.npmrc
            - run: echo "@espressive:registry=https://npm.pkg.github.com" >> ~/.npmrc
          <<: *post_steps
      - lint:
          <<: *post_steps
          requires:
            - install
      - test:
          <<: *post_steps
          requires:
            - install
      - build-cascara:
          <<: *post_steps
          requires:
            - install
      - build-cosmos:
          <<: *post_steps
          requires:
            - lint
            - test
      - release:
          filters:
            branches:
              only: main
          requires:
            - build-cascara
