version: 2.1

orbs:
  node: circleci/node@3.0.1
  slack: circleci/slack@3.4.2

jobs:
  install:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - '*'
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  lint:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Eslint
          command: yarn lint
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  test:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Unit Tests
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-cascara:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build Cascara Runtimes
          command: make
      - save_cache:
          key: cascara-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/cjs
            - /home/circleci/project/packages/cascara/es
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-cosmos:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build Cosmos
          command: yarn cosmos:build
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

  build-docs:
    executor:
      name: node/default
      tag: '14.5.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          key: cascara-{{ .Revision }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/project/packages/cascara/cjs
            - /home/circleci/project/packages/cascara/es
      - run:
          name: Build Docs
          command: yarn docs build
      - slack/status:
          fail_only: true
          include_project_field: false
          mentions: 'bje'

workflows:
  build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build-cascara:
          requires:
            - install
      - build-cosmos:
          requires:
            - lint
            - test
      - build-docs:
          requires:
            - build-cascara
            - lint
            - test
