version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - slack/status:
                # fail_only: true
                mentions: 'bje'
                webhook: webhook
workflows:
  build-and-test:
    jobs:
      - build-and-test
