# This action will update any of our PRs that are out of date with their target branch.
# tibdex/auto-update@v1 will only log the issue if there is a failure, usually due to conflicts
# https://github.com/tibdex/auto-update/issues/2

name: Auto-update
on:
  push:
    # If pull requests are always based on the same branches, only triggering the workflow when these branches receive new commits will minimize the workflow execution.
    branches:
      - develop
      - main

jobs:
  auto:
    name: Auto Update PRs
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/auto-update@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment to ignore pull requests without the specified label.
          # label: auto-update
