# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/create-or-update-comment

name: Epic Label

# Controls when the action will run. 
on:
  # Triggers when a pull request is labeled
  pull_request:
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "epic_comment"
  epic_comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Only runs if the pull_request has a label of 'Epic'
    if: contains( github.event.pull_request.labels.*.name, 'Epic')

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Test Epic Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This comment was written by a bot!
          reaction-type: "rocket"


